# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "rancher-server" do |server|
    server.vm.box = "ubuntu/xenial64"

    server.vm.network "forwarded_port", guest: 9090, host: 9090

    server.vm.synced_folder "./data", "/vagrant"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    server.dns.tld = "dev"
    server.vm.hostname = "rancher-server"
    # server.vm.network "private_network", type: "dhcp"
    server.vm.network "private_network", ip: "172.28.128.3"


    server.vm.provision "shell", inline: <<-SHELL
       apt-get update
       apt-get install -y docker.io
       service docker start
       docker run -d --restart=unless-stopped -p 9090:8080 rancher/server
       apt-get install -y httpie
       apt-get install -y jq

       export RANCHER_URL="http://localhost:9090/"

       export RANCHER_KEY_RESPONSE=$(http --ignore-stdin --print b \
        POST ${RANCHER_URL}v2-beta/apikey \
        type=apikey accountId=1a1 name=roboto)

       export RANCHER_ACCESS_KEY=$(echo $RANCHER_KEY_RESPONSE \
        | jq --raw-output " . | .secretValue" )

       export RANCHER_SECRET_KEY=$(echo $RANCHER_KEY_RESPONSE \
        | jq --raw-output " . | .publicValue" )

       echo "Generated Key: $RANCHER_SECRET_KEY and $RANCHER_ACCESS_KEY"

       curl -o compose.tar.gz https://releases.rancher.com/compose/v0.12.1/rancher-compose-linux-amd64-v0.12.1.tar.gz

       tar -zxvf compose.tar.gz ./rancher-compose-v0.12.1/rancher-compose -C .
       cp ./rancher-compose-v0.12.1/rancher-compose /usr/bin/rancher-compose

       chmod u+x /usr/bin/rancher-compose

       rancher-compose --version

       rancher-compose --verbose --file /vagrant/docker-compose.yml up

    SHELL

  end

  config.vm.define "rancher-host" do |host|
    host.vm.box = "ubuntu/xenial64"

    host.vm.network "forwarded_port", guest: 8081, host: 8081

    host.vm.synced_folder "./data", "/vagrant"

    host.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end

    host.dns.tld = "dev"
    host.vm.hostname = "rancher-host"

    host.vm.network "private_network", ip: "172.28.128.4"

    host.vm.provision "shell", inline: <<-SHELL
       apt-get update
       apt-get install -y docker.io
       service docker start
    SHELL
  end

  config.vm.define "rancher-host2" do |host|
    host.vm.box = "ubuntu/xenial64"

    host.vm.network "forwarded_port", guest: 8081, host: 8082

    host.vm.synced_folder "./data", "/vagrant"

    host.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end

    host.dns.tld = "dev"
    host.vm.hostname = "rancher-host2"

    host.vm.network "private_network", ip: "172.28.128.5"

    host.vm.provision "shell", inline: <<-SHELL
       apt-get update
       apt-get install -y docker.io
       service docker start
    SHELL
  end

end
